### ISSUE TITLE
Plugin wishlist

### ISSUE THREAD

**Issue by hyochan** [NodeBB/nodebb-plugin-quickstart#174]
Hello. I am not sure where I can post the wishlist for the plugin.

It'd be really great if there is an official slack integration plugin.

I've tried all community plugins and they are not working in `2.x`.

Related https://github.com/pichalite/nodebb-plugin-slack-extended/issues/13

**Comment by julianlam** [comment]
Please open an issue on the slack plugins that are not working, this is just the issue tracker for the quickstart template, thanks!
