### ISSUE TITLE
full documentation?

### ISSUE THREAD

**Issue by k1r0s** [NodeBB/nodebb-plugin-quickstart#263]
Im trying to update this plugin to the latest version:

https://github.com/psychobunny/nodebb-plugin-desktop-notifications

after installing and activating it I get `Uncaught (in promise) TypeError: app.alert is not a function` here: https://github.com/psychobunny/nodebb-plugin-desktop-notifications/blob/master/public/lib/main.js#L18

I'm searching for the documentation so I can fix this issue to keep this thing going. Any help?¿

Thx

**Comment by k1r0s** [comment]
ok, nvm. This plugin does not support offline notifications

**Comment by julianlam** [comment]
https://github.com/psychobunny/nodebb-plugin-desktop-notifications/issues/38
