### ISSUE TITLE
Unable to load template: admin/plugins/quickstart (Not Found)

### ISSUE THREAD

**Issue by jonnybcz** [NodeBB/nodebb-plugin-quickstart#4]
Hi,

i have nodebb v1.4.4. I install plugin over npm install nodebb-plugin-quickstart. In administration after click on **plugins** > **quickstart** console says: _Unable to load template: admin/plugins/quickstart (Not Found)_

**Comment by julianlam** [comment]
This plugin is not meant to be installed directly into NodeBB, but forked into your own plugin.

Also your probably need to run ./nodebb build.
