### ISSUE TITLE
error: 404 Not Found

### ISSUE THREAD

**Issue by johnking** [NodeBB/nodebb-plugin-quickstart#7]
In README.md, 

...
Once you're done don't forget to publish it on NPM, and make a thread about it [here](https://docs.nodebb.org/en/latest/plugins/hooks.html).
...

after clicking link [here](https://docs.nodebb.org/en/latest/plugins/hooks.html), it gives me a 404 error page.

**Comment by julianlam** [comment]
That's odd, not sure why it even points to that page :thinking:
